
TIMEZONES = [
  'Etc/GMT+12', 'Pacific/Midway', 'Pacific/Pago_Pago', 'Pacific/Honolulu',
  'America/Juneau', 'America/Los_Angeles', 'America/Tijuana', 'America/Denver',
  'America/Phoenix', 'America/Chihuahua', 'America/Chicago', 'America/Regina',
  'America/Mexico_City', 'America/Belize', 'America/Detroit',
  'America/Indiana/Indianapolis', 'America/Bogota', 'America/Glace_Bay',
  'America/Halifax', 'America/Caracas', 'America/Santo_Domingo',
  'America/Argentina/Buenos_Aires', 'America/Santiago', 'America/St_Johns',
  'America/Sao_Paulo', 'America/Godthab', 'America/Montevideo',
  'Atlantic/South_Georgia', 'Atlantic/Azores', 'Atlantic/Cape_Verde',
  'Africa/Casablanca', 'Etc/Greenwich', 'Europe/London', 'Europe/Amsterdam',
  'Europe/Belgrade', 'Europe/Brussels', 'Europe/Sarajevo', 'Africa/Lagos',
  'Asia/Amman', 'Europe/Athens', 'Asia/Beirut', 'Africa/Cairo',
  'Africa/Harare', 'Europe/Helsinki', 'Asia/Jerusalem', 'Europe/Minsk',
  'Africa/Windhoek', 'Asia/Kuwait', 'Europe/Moscow', 'Asia/Baghdad',
  'Asia/Riyadh', 'Africa/Nairobi', 'Asia/Tehran', 'Asia/Muscat', 'Asia/Baku',
  'Asia/Tbilisi', 'Asia/Yerevan', 'Asia/Kabul', 'Asia/Yekaterinburg',
  'Asia/Karachi', 'Asia/Tashkent', 'Asia/Kolkata', 'Asia/Colombo',
  'Asia/Kathmandu', 'Asia/Almaty', 'Asia/Dhaka', 'Asia/Urumqi', 'Asia/Rangoon',
  'Asia/Bangkok', 'Asia/Jakarta', 'Asia/Krasnoyarsk', 'Asia/Shanghai',
  'Asia/Chongqing', 'Asia/Hong_Kong', 'Asia/Irkutsk', 'Asia/Kuala_Lumpur',
  'Australia/Perth', 'Asia/Singapore', 'Asia/Taipei', 'Asia/Ulaanbaatar',
  'Asia/Tokyo', 'Asia/Yakutsk', 'Australia/Adelaide', 'Australia/Darwin',
  'Australia/Brisbane', 'Australia/Sydney', 'Pacific/Guam', 'Australia/Hobart',
  'Pacific/Port_Moresby', 'Asia/Vladivostok', 'Asia/Magadan', 'Asia/Kamchatka',
  'Pacific/Auckland', 'Pacific/Fiji', 'Pacific/Tongatapu'
]
